name: Release helm

on:
  push:
    branches:
      - main


jobs:
  bump-version:
    name: Unionoperator Bump Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump-version.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Bump version and push tag
        id: bump-version
        uses: mayitbeegh/github-tag-action@1.17.4
        # There's a new Git CVE announced two weeks ago which (with the new Git update) broke actions that depend on Git. (https://github.blog/2022-04-12-git-security-vulnerability-announced/)
        # This issue is fixed in anothrNick/github-tag-action@1.39.0 but it introduced another issue which prevents the action from working properly on versions that start with "v".
        # I (Sean) took anothrNick/github-tag-action@1.17.2 and added the Git fix as a temporary solution until the "v" issue is fixed.
        # See diff here (https://github.com/mayitbeegh/github-tag-action/commit/3a9f28ceef4d67adcaad320cabf719aa635e5a60)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: patch

  helm-release:
    name: Unionoperator helm release
    runs-on: ubuntu-latest
    needs: [bump-version]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Install Helm
        uses: azure/setup-helm@v1
      - name: Update Version in helm
        run: |
          sed "s/v0.0.1/${{ needs.bump-version.outputs.version }}/g" ./charts/unionoperator/README.md  > temp.txt && mv temp.txt ./charts/unionoperator/README.md
          grep -rlZ "version:[^P]*# VERSION" ./charts/unionoperator/Chart.yaml | xargs -0 sed -i "s/version:[^P]*# VERSION/version: ${{ needs.bump-version.outputs.version }} # VERSION/g"
          grep -rlZ "appVersion:[^P]*# APP_VERSION" ./charts/unionoperator/Chart.yaml | xargs -0 sed -i "s/appVersion:[^P]*# APP_VERSION/appVersion: ${{ needs.bump-version.outputs.version }} # APP_VERSION/g"
      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
      - name: Run chart-releaser
        uses: stefanprodan/helm-gh-pages@v1.4.1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          linting: off
